import type { AdminSeed, Hairdresser } from "@/lib/types";

export const hairdressers: Hairdresser[] = [
  {
    id: "hd-001",
    trustCutId: "TC-2026-004812",
    photos: ["/hairdressers/mali.svg"],
    idPhoto: "/hairdressers/id-card-mali.svg",
    firstName: "Mali",
    lastName: "Kanchana",
    nickName: "May",
    hometownAddress: "Mueang Chiang Mai, Chiang Mai",
    currentAddress: "Sathon, Bangkok",
    phone: "+66 81 222 0148",
    email: "mali.k@example.com",
    lineId: "may.cut",
    instagram: "@maytexture",
    socialMedia: ["Instagram", "TikTok"],
    yearsExperience: 8,
    specialties: ["Layered cut", "Balayage", "Client consultation"],
    workHistory: ["2018-2021: Urban Fringe Chiang Mai", "2021-2026: Nine Chair Studio Bangkok"],
    certificates: ["Advanced Color Correction", "Hygiene and Salon Safety"],
    competency: [
      { label: "Cutting", score: 92 },
      { label: "Color", score: 88 },
      { label: "Styling", score: 84 },
      { label: "Sanitation", score: 95 },
      { label: "Consulting", score: 91 },
    ],
    aptitude: [
      { label: "Learning", score: 89 },
      { label: "Speed", score: 82 },
      { label: "Detail", score: 93 },
      { label: "Teamwork", score: 86 },
      { label: "Pressure", score: 88 },
    ],
    behaviorScore: 91,
    reliabilityScore: 94,
    pdpaAcceptedAt: "2026-05-02T09:00:00.000Z",
    lastVerifiedAt: "2026-06-26T10:30:00.000Z",
    comments: [
      {
        id: "c-001",
        authorName: "Anan S.",
        salonName: "Nine Chair Studio",
        body: "Strong client consultation and dependable hygiene routine. Works best when color bookings are well scoped.",
        rating: 5,
        status: "approved",
        createdAt: "2026-06-21T07:30:00.000Z",
      },
      {
        id: "c-002",
        authorName: "Pat N.",
        salonName: "Sukhumvit Cut Lab",
        body: "Portfolio check requested for formal updo work before assigning bridal packages.",
        rating: 4,
        status: "pending",
        createdAt: "2026-06-30T12:00:00.000Z",
      },
    ],
    styles: [
      {
        id: "s-001",
        title: "Soft Layer Refresh",
        imageUrl: "/styles/soft-layer.svg",
        description: "Long layered refresh with low-maintenance shape for humid weather.",
        postedBy: "Mali K.",
        createdAt: "2026-06-10T08:00:00.000Z",
      },
      {
        id: "s-002",
        title: "Warm Balayage",
        imageUrl: "/styles/balayage.svg",
        description: "Warm brunette balayage with face-framing highlights.",
        postedBy: "Mali K.",
        createdAt: "2026-06-18T08:00:00.000Z",
      },
    ],
  },
  {
    id: "hd-002",
    trustCutId: "TC-2026-006197",
    photos: ["/hairdressers/niran.svg"],
    idPhoto: "/hairdressers/id-card-niran.svg",
    firstName: "Niran",
    lastName: "Wongchai",
    nickName: "Nin",
    hometownAddress: "Hat Yai, Songkhla",
    currentAddress: "Ari, Bangkok",
    phone: "+66 88 410 7719",
    email: "niran.w@example.com",
    lineId: "nin.fade",
    instagram: "@ninfades",
    socialMedia: ["Instagram", "Facebook"],
    yearsExperience: 6,
    specialties: ["Fade", "Clipper work", "Beard trim"],
    workHistory: ["2020-2023: Southside Barber House", "2023-2026: Ari Barber Collective"],
    certificates: ["Classic Barbering", "Client Care Basics"],
    competency: [
      { label: "Cutting", score: 90 },
      { label: "Color", score: 54 },
      { label: "Styling", score: 80 },
      { label: "Sanitation", score: 92 },
      { label: "Consulting", score: 83 },
    ],
    aptitude: [
      { label: "Learning", score: 84 },
      { label: "Speed", score: 94 },
      { label: "Detail", score: 88 },
      { label: "Teamwork", score: 79 },
      { label: "Pressure", score: 90 },
    ],
    behaviorScore: 86,
    reliabilityScore: 89,
    pdpaAcceptedAt: "2026-04-14T11:00:00.000Z",
    lastVerifiedAt: "2026-06-20T14:15:00.000Z",
    comments: [
      {
        id: "c-003",
        authorName: "Siriporn T.",
        salonName: "Ari Barber Collective",
        body: "Very fast on repeat fade clients. Needs clear booking buffer for first-time consultations.",
        rating: 4,
        status: "approved",
        createdAt: "2026-06-13T09:20:00.000Z",
      },
    ],
    styles: [
      {
        id: "s-003",
        title: "Low Skin Fade",
        imageUrl: "/styles/low-fade.svg",
        description: "Low fade with textured top and natural side profile.",
        postedBy: "Niran W.",
        createdAt: "2026-06-24T08:00:00.000Z",
      },
    ],
  },
  {
    id: "hd-003",
    trustCutId: "TC-2026-007452",
    photos: ["/hairdressers/pim.svg"],
    idPhoto: "/hairdressers/id-card-pim.svg",
    firstName: "Pimchanok",
    lastName: "Rattanaporn",
    nickName: "Pim",
    hometownAddress: "Mueang Khon Kaen, Khon Kaen",
    currentAddress: "Thong Lo, Bangkok",
    phone: "+66 82 913 6680",
    email: "pim.r@example.com",
    lineId: "pim.bridal",
    instagram: "@pimbridalhair",
    socialMedia: ["Instagram", "YouTube"],
    yearsExperience: 11,
    specialties: ["Bridal updo", "Formal styling", "Extensions"],
    workHistory: ["2015-2019: Crown Salon Khon Kaen", "2019-2026: Maison Glow Bangkok"],
    certificates: ["Bridal Styling Masterclass", "Hair Extension Safety"],
    competency: [
      { label: "Cutting", score: 76 },
      { label: "Color", score: 81 },
      { label: "Styling", score: 96 },
      { label: "Sanitation", score: 90 },
      { label: "Consulting", score: 94 },
    ],
    aptitude: [
      { label: "Learning", score: 86 },
      { label: "Speed", score: 78 },
      { label: "Detail", score: 97 },
      { label: "Teamwork", score: 91 },
      { label: "Pressure", score: 93 },
    ],
    behaviorScore: 95,
    reliabilityScore: 92,
    pdpaAcceptedAt: "2026-03-09T09:30:00.000Z",
    lastVerifiedAt: "2026-06-28T16:30:00.000Z",
    comments: [
      {
        id: "c-004",
        authorName: "Kanda M.",
        salonName: "Maison Glow",
        body: "Excellent with premium styling clients. Calm during event-day pressure and keeps clear notes.",
        rating: 5,
        status: "approved",
        createdAt: "2026-06-05T13:00:00.000Z",
      },
    ],
    styles: [
      {
        id: "s-004",
        title: "Modern Bridal Chignon",
        imageUrl: "/styles/bridal-chignon.svg",
        description: "Structured low chignon with polished face frame.",
        postedBy: "Pimchanok R.",
        createdAt: "2026-06-12T08:00:00.000Z",
      },
    ],
  },
  {
    id: "hd-004",
    trustCutId: "TC-2026-008023",
    photos: ["/hairdressers/krit.svg"],
    idPhoto: "/hairdressers/id-card-krit.svg",
    firstName: "Krit",
    lastName: "Suwan",
    nickName: "Kit",
    hometownAddress: "Mueang Rayong, Rayong",
    currentAddress: "Phra Khanong, Bangkok",
    phone: "+66 86 515 2004",
    email: "krit.s@example.com",
    lineId: "kit.colorlab",
    instagram: "@kitcolorlab",
    socialMedia: ["Instagram", "TikTok"],
    yearsExperience: 5,
    specialties: ["Creative color", "Bleach care", "Short textured cuts"],
    workHistory: ["2021-2024: Rayong Color Room", "2024-2026: Phra Khanong Color Lab"],
    certificates: ["Bleach and Tone Systems", "Scalp Protection"],
    competency: [
      { label: "Cutting", score: 82 },
      { label: "Color", score: 93 },
      { label: "Styling", score: 79 },
      { label: "Sanitation", score: 88 },
      { label: "Consulting", score: 85 },
    ],
    aptitude: [
      { label: "Learning", score: 92 },
      { label: "Speed", score: 77 },
      { label: "Detail", score: 90 },
      { label: "Teamwork", score: 84 },
      { label: "Pressure", score: 80 },
    ],
    behaviorScore: 82,
    reliabilityScore: 84,
    pdpaAcceptedAt: "2026-05-21T15:00:00.000Z",
    lastVerifiedAt: "2026-06-18T09:45:00.000Z",
    comments: [
      {
        id: "c-005",
        authorName: "Ben C.",
        salonName: "Color Lab",
        body: "Strong creative work. Admin should review late-arrival reports before premium shift assignment.",
        rating: 3,
        status: "approved",
        createdAt: "2026-06-11T10:00:00.000Z",
      },
    ],
    styles: [
      {
        id: "s-005",
        title: "Copper Crop",
        imageUrl: "/styles/copper-crop.svg",
        description: "Warm copper crop with controlled lift and gloss finish.",
        postedBy: "Krit S.",
        createdAt: "2026-06-26T08:00:00.000Z",
      },
    ],
  },
  {
    id: "hd-005",
    trustCutId: "TC-2026-009184",
    photos: ["/hairdressers/mali.svg"],
    idPhoto: "/hairdressers/id-card-mali.svg",
    firstName: "Chanida",
    lastName: "Srisawat",
    nickName: "Nida",
    hometownAddress: "Mueang Phuket, Phuket",
    currentAddress: "Ekkamai, Bangkok",
    phone: "+66 89 204 7712",
    email: "chanida.s@example.com",
    lineId: "nida.color",
    instagram: "@nidacolorwork",
    socialMedia: ["Instagram", "TikTok"],
    yearsExperience: 7,
    specialties: ["Color correction", "Gloss treatment", "Consultation"],
    workHistory: ["2019-2022: Andaman Hair Studio", "2022-2026: Ekkamai Color House"],
    certificates: ["Color Correction Intensive", "Keratin Treatment Safety"],
    competency: [
      { label: "Cutting", score: 78 },
      { label: "Color", score: 94 },
      { label: "Styling", score: 82 },
      { label: "Sanitation", score: 91 },
      { label: "Consulting", score: 90 },
    ],
    aptitude: [
      { label: "Learning", score: 90 },
      { label: "Speed", score: 80 },
      { label: "Detail", score: 92 },
      { label: "Teamwork", score: 87 },
      { label: "Pressure", score: 86 },
    ],
    behaviorScore: 88,
    reliabilityScore: 90,
    pdpaAcceptedAt: "2026-05-30T10:00:00.000Z",
    lastVerifiedAt: "2026-06-29T11:30:00.000Z",
    comments: [
      {
        id: "c-006",
        authorName: "Natcha P.",
        salonName: "Ekkamai Color House",
        body: "Careful consultation and strong correction planning. Good candidate for senior colorist shifts.",
        rating: 5,
        status: "approved",
        createdAt: "2026-06-25T09:00:00.000Z",
      },
    ],
    styles: [
      {
        id: "s-006",
        title: "Glossy Espresso Brown",
        imageUrl: "/styles/balayage.svg",
        description: "Gloss refresh for brunette clients with low-damage color maintenance.",
        postedBy: "Chanida S.",
        createdAt: "2026-06-27T08:00:00.000Z",
      },
    ],
  },
  {
    id: "hd-006",
    trustCutId: "TC-2026-009662",
    photos: ["/hairdressers/niran.svg"],
    idPhoto: "/hairdressers/id-card-niran.svg",
    firstName: "Teerapat",
    lastName: "Jaroen",
    nickName: "Top",
    hometownAddress: "Mueang Nakhon Ratchasima, Nakhon Ratchasima",
    currentAddress: "Ratchathewi, Bangkok",
    phone: "+66 92 771 4450",
    email: "teerapat.j@example.com",
    lineId: "top.barber",
    instagram: "@topclassicbarber",
    socialMedia: ["Instagram", "Facebook"],
    yearsExperience: 9,
    specialties: ["Classic cut", "Executive grooming", "Beard shaping"],
    workHistory: ["2017-2020: Korat Gentlemen Barber", "2020-2026: Ratchathewi Groom Room"],
    certificates: ["Classic Scissor Cutting", "Barber Hygiene Standard"],
    competency: [
      { label: "Cutting", score: 95 },
      { label: "Color", score: 45 },
      { label: "Styling", score: 86 },
      { label: "Sanitation", score: 93 },
      { label: "Consulting", score: 89 },
    ],
    aptitude: [
      { label: "Learning", score: 82 },
      { label: "Speed", score: 91 },
      { label: "Detail", score: 94 },
      { label: "Teamwork", score: 84 },
      { label: "Pressure", score: 92 },
    ],
    behaviorScore: 90,
    reliabilityScore: 93,
    pdpaAcceptedAt: "2026-04-04T09:00:00.000Z",
    lastVerifiedAt: "2026-06-30T13:10:00.000Z",
    comments: [
      {
        id: "c-007",
        authorName: "Vichai R.",
        salonName: "Ratchathewi Groom Room",
        body: "Punctual, consistent, and excellent with regular executive clients.",
        rating: 5,
        status: "approved",
        createdAt: "2026-06-19T09:00:00.000Z",
      },
      {
        id: "c-008",
        authorName: "Mook S.",
        salonName: "Central Barber Hub",
        body: "Requesting admin review for weekend availability history before hiring.",
        rating: 4,
        status: "pending",
        createdAt: "2026-07-01T12:30:00.000Z",
      },
    ],
    styles: [
      {
        id: "s-007",
        title: "Executive Taper",
        imageUrl: "/styles/low-fade.svg",
        description: "Clean taper with natural business styling.",
        postedBy: "Teerapat J.",
        createdAt: "2026-06-29T08:00:00.000Z",
      },
    ],
  },
  {
    id: "hd-007",
    trustCutId: "TC-2026-010104",
    photos: ["/hairdressers/pim.svg"],
    idPhoto: "/hairdressers/id-card-pim.svg",
    firstName: "Sasithorn",
    lastName: "Phanich",
    nickName: "Sai",
    hometownAddress: "Mueang Ubon Ratchathani, Ubon Ratchathani",
    currentAddress: "Lat Phrao, Bangkok",
    phone: "+66 95 310 6294",
    email: "sasithorn.p@example.com",
    lineId: "sai.extension",
    instagram: "@saihairext",
    socialMedia: ["Instagram", "YouTube"],
    yearsExperience: 10,
    specialties: ["Extensions", "Scalp consultation", "Event styling"],
    workHistory: ["2016-2021: Ubon Beauty Loft", "2021-2026: Lat Phrao Extension Studio"],
    certificates: ["Extension Placement Safety", "Scalp and Hair Loss Basics"],
    competency: [
      { label: "Cutting", score: 80 },
      { label: "Color", score: 84 },
      { label: "Styling", score: 92 },
      { label: "Sanitation", score: 94 },
      { label: "Consulting", score: 95 },
    ],
    aptitude: [
      { label: "Learning", score: 87 },
      { label: "Speed", score: 76 },
      { label: "Detail", score: 96 },
      { label: "Teamwork", score: 90 },
      { label: "Pressure", score: 88 },
    ],
    behaviorScore: 93,
    reliabilityScore: 91,
    pdpaAcceptedAt: "2026-06-03T08:45:00.000Z",
    lastVerifiedAt: "2026-06-25T15:00:00.000Z",
    comments: [
      {
        id: "c-009",
        authorName: "Jariya K.",
        salonName: "Lat Phrao Extension Studio",
        body: "Strong detail and very good aftercare education for clients.",
        rating: 5,
        status: "approved",
        createdAt: "2026-06-22T10:00:00.000Z",
      },
    ],
    styles: [
      {
        id: "s-008",
        title: "Seamless Volume Extension",
        imageUrl: "/styles/bridal-chignon.svg",
        description: "Natural volume extension with tidy placement and client aftercare.",
        postedBy: "Sasithorn P.",
        createdAt: "2026-06-21T08:00:00.000Z",
      },
    ],
  },
  {
    id: "hd-008",
    trustCutId: "TC-2026-010876",
    photos: ["/hairdressers/krit.svg"],
    idPhoto: "/hairdressers/id-card-krit.svg",
    firstName: "Arthit",
    lastName: "Lertchai",
    nickName: "Art",
    hometownAddress: "Mueang Surat Thani, Surat Thani",
    currentAddress: "On Nut, Bangkok",
    phone: "+66 91 448 5021",
    email: "arthit.l@example.com",
    lineId: "art.texture",
    instagram: "@arttexturecut",
    socialMedia: ["Instagram", "TikTok"],
    yearsExperience: 4,
    specialties: ["Texture cut", "Perm support", "Men's styling"],
    workHistory: ["2022-2024: Surat Texture Bar", "2024-2026: On Nut Studio"],
    certificates: ["Texture Cutting Foundation", "Chemical Service Support"],
    competency: [
      { label: "Cutting", score: 86 },
      { label: "Color", score: 62 },
      { label: "Styling", score: 88 },
      { label: "Sanitation", score: 87 },
      { label: "Consulting", score: 78 },
    ],
    aptitude: [
      { label: "Learning", score: 91 },
      { label: "Speed", score: 85 },
      { label: "Detail", score: 83 },
      { label: "Teamwork", score: 88 },
      { label: "Pressure", score: 79 },
    ],
    behaviorScore: 84,
    reliabilityScore: 82,
    pdpaAcceptedAt: "2026-06-09T10:20:00.000Z",
    lastVerifiedAt: "2026-06-26T17:20:00.000Z",
    comments: [
      {
        id: "c-010",
        authorName: "Oat T.",
        salonName: "On Nut Studio",
        body: "Promising junior stylist. Best paired with a senior colorist for chemical services.",
        rating: 4,
        status: "approved",
        createdAt: "2026-06-17T09:30:00.000Z",
      },
    ],
    styles: [
      {
        id: "s-009",
        title: "Textured Crop",
        imageUrl: "/styles/copper-crop.svg",
        description: "Short textured cut with easy daily styling.",
        postedBy: "Arthit L.",
        createdAt: "2026-06-20T08:00:00.000Z",
      },
    ],
  },
];

export const adminSeed: AdminSeed = {
  members: [
    {
      id: "mem-001",
      name: "Natcha Prasert",
      salonName: "Sukhumvit Cut Lab",
      role: "owner",
      email: "natcha@example.com",
      status: "active",
      lastGpsCheck: "2026-07-03T09:10:00.000Z",
    },
    {
      id: "mem-002",
      name: "Anan S.",
      salonName: "Nine Chair Studio",
      role: "manager",
      email: "anan@example.com",
      status: "active",
      lastGpsCheck: "2026-07-02T12:00:00.000Z",
    },
    {
      id: "mem-003",
      name: "Patchara N.",
      salonName: "New Salon Group",
      role: "owner",
      email: "patchara@example.com",
      status: "pending",
      lastGpsCheck: "2026-06-29T08:40:00.000Z",
    },
    {
      id: "mem-004",
      name: "Vichai R.",
      salonName: "Ratchathewi Groom Room",
      role: "owner",
      email: "vichai@example.com",
      status: "active",
      lastGpsCheck: "2026-07-03T13:45:00.000Z",
    },
    {
      id: "mem-005",
      name: "Jariya K.",
      salonName: "Lat Phrao Extension Studio",
      role: "manager",
      email: "jariya@example.com",
      status: "active",
      lastGpsCheck: "2026-07-01T17:10:00.000Z",
    },
    {
      id: "mem-006",
      name: "Oat T.",
      salonName: "On Nut Studio",
      role: "owner",
      email: "oat@example.com",
      status: "suspended",
      lastGpsCheck: "2026-06-18T12:30:00.000Z",
    },
  ],
  usageStats: [
    { label: "Verified lookups", value: "1,684", trend: "+22% this month" },
    { label: "Pending comments", value: "8", trend: "Needs admin approval" },
    { label: "Active salons", value: "45", trend: "+8 approved" },
    { label: "GPS denials", value: "23", trend: "-6% from June" },
  ],
};
